name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install texlive
      uses: teatimeguest/setup-texlive-action@v3.0.1
      with:
        packages: >-
          dvips
          dvipdfmx
          dvisvgm
          scheme-basic
          hyperref
          collection-langcyrillic
          graphics
          tools
          amscls
          latexmk
          tex4ht
          appendix
          csquotes
          titlesec
          multirow
          mathtools
          amsfonts
          gensymb
          todonotes
          adjustbox
          enumitem
          capt-of
          titling
          import

    - name: Install calibre
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: calibre
          

    - name: Create PDF/epub files
      run: make

    - name: Generate release tag
      id: generate_release_tag
      uses: alexvingg/next-release-tag@v1.0.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: ''

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.generate_release_tag.outputs.release_tag }}
        release_name: Release ${{ steps.generate_release_tag.outputs.release_tag }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          math.pdf
          inf.pdf
          full.pdf
          math.epub
          inf.epub
          full.epub
        tag_name: ${{ steps.generate_release_tag.outputs.release_tag }}
