name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install texlive
      uses: teatimeguest/setup-texlive-action@v3.0.1
      with:
        packages: >-
          scheme-basic
          hyperref
          collection-langcyrillic
          latexmk
          tex4ht
          csquotes
          titlesec
          multirow
          multicol
          indentfirst
          tabularx
          mathtools
          amssymb
          amsfonts
          textcomp
          amsthm
          gensymb
          graphicx
          todonotes
          adjustbox
          enumerate
          enumitem
          capt-of
          titling
          import

    - name: Install calibre
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: calibre
          

    - name: Create PDF/epub files
      run: make

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: math.pdf inf.pdf full.pdf math.epub inf.epub full.epub
