name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install texlive
      uses: teatimeguest/setup-texlive-action@v3.0.1

    - name: Install calibre
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: calibre

    - name: Create PDF/epub files
      run: make
